FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y bash curl docker.io postgresql-client && \
    apt-get clean

WORKDIR /app

COPY ./scripts ./scripts
COPY .env .env
COPY docker-compose.yml docker-compose.yml
