services:
   postgres:
     image: postgres:16
     container_name: my_postgres
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: we_got_jira_at_home
     ports:
       - '5432:5432'
     volumes:
       - postgres_data:/var/lib/postgresql/data
     healthcheck:
       test: ['CMD-SHELL', 'pg_isready -U postgres -d we_got_jira_at_home']
       interval: 10s
       timeout: 5s
       retries: 5
     restart: unless-stopped

volumes:
   postgres_data:
