services:
  env-init:
    image: wegotjira-init
    container_name: wegotjira-env-init
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["bash", "./scripts/init-env.sh"]
  init:
    image: wegotjira-init
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    entrypoint: ["bash", "./scripts/create-dbs.sh"]
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
  app:
    build: .
    container_name: weGotJiraAtHome
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    tty: true
    stdin_open: true

  db:
    image: postgres:16
    container_name: my_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
