#!/bin/bash
set -e

echo "🧪 Starting lite initialization..."

ENV_FILE=".env"

if [[ -f "$ENV_FILE" ]]; then
  read -p "⚠️  .env file already exists. Overwrite? (y/N): " CONFIRM
  if [[ "$CONFIRM" != "y" && "$CONFIRM" != "Y" ]]; then
    echo "❌ Aborting setup."
    exit 1
  fi
fi

read -p "Enter the database name: " DB_NAME
read -p "Enter the database user: " DB_USER
read -s -p "Enter password for DB user: " DB_PASSWORD
echo ""
read -s -p "Enter JWT secret (or leave blank to generate one): " JWT_SECRET
echo ""

if [[ -z "$JWT_SECRET" ]]; then
  JWT_SECRET=$(openssl rand -hex 32)
  echo "🔐 Generated JWT secret: $JWT_SECRET"
fi

cat > "$ENV_FILE" <<EOL
# Auto-generated by init-env.sh
APP_MESSAGE_PREFIX=HelloWorld

DB_HOST=db
DB_PORT=5432  # replace if already in use
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD
DB_SYNC=0     # remove 0 for production and work with migrations

JWT_SECRET=$JWT_SECRET
JWT_EXPIRES_IN=60m
EOL

echo "✅ .env file created with basic config!"
